### ISSUE TITLE
Support for new versions

### ISSUE THREAD

**Issue by Zarkness2** [Ynfuien/SuperiorSkyblockExtraFlags#1]
my issue is to ask for support for new versions

**Comment by Ynfuien** [comment]
Have you tried using this plugin on new versions? Because for me everything looks fine on Purpur 1.18.2 with build 665 of SS2

**Comment by Zarkness2** [comment]
I didn't get to try it but since it said it only supported 1.17 I thought it wouldn't work with 1.18.2.

**Comment by Ynfuien** [comment]
It says
"Made for version 1.17.1 **but might work with other ones**."

True, I didn't say exactly that it will work on new versions, but also I didn't say that it only works on 1.17 😉
But since I tested it in general yesterday with 1.18, you are free to try it by yourself

**Comment by Zarkness2** [comment]
ok, thank you very much, a question that has nothing to do with this plugin but I can not find any and maybe you know of one, you do not know of any addon for superiorskyblock that update today that when a user creates an island creates an npc, as has hypixel skyblock? @Ynfuien

**Comment by Zarkness2** [comment]
is that the only one I know 1 is not even finished and the other one gives me an error when I put it in

**Comment by Ynfuien** [comment]
Sorry, I don't know any. Anything that comes me to mind, is that if you had already plugin for npc but without support for SS2, then you could use `event-commands` section in SS2's config for spawnig those npcs on islands

**Comment by Zarkness2** [comment]
could you give me an example of how it would be? I would like to use an addon for that because I would already have the system so that they can move the npc anywhere etc..., that in itself with a command that gives the user an egg or an item to place it where you want and I would get, then the theme of menus and I would do it with a plugin menus

**Comment by Ynfuien** [comment]
It's just a quick idea. In SS2's config in `event-commands` section you can add any command to fire on any SS2's event.
```
# A list of commands that will be executed when an event is called.
# You can find a list of events at @ https://bg-software.com/superiorskyblock/api/
# A list of placeholders (Not all of them work for all the events):
# %island% %player% %schematic% %enter-cause% %target% %leave-cause% %old-owner% %new-owner% %worth% %level%
event-commands:
  IslandCreateEvent:
    - 'give_egg_or_whatever %player%'
```

**Comment by Zarkness2** [comment]
I do not want to give them an egg when they create the island what I want is to create the island the npc is in the area where I set it as has the skyblock of hypixel, then the egg would be so that the user to run a command can move the npc to another side.

**Comment by Zarkness2** [comment]
I was thinking of using this https://github.com/mdaffa48/IslandNPC which is quite good but the bad thing is that it gives me an error when I start it and I think it is abandoned.

**Comment by Ynfuien** [comment]
This plugin depends on Citizens. Do you have it on server?

**Comment by Zarkness2** [comment]
I know and I have the citizens and it still doesn't work.

**Comment by Zarkness2** [comment]
I opened an issue in the plugin with the error I was getting

**Comment by Zarkness2** [comment]
https://github.com/mdaffa48/IslandNPC/issues/2

**Comment by Ynfuien** [comment]
I see author of plugin just answered. Hope he would fix this bug soon

**Comment by Zarkness2** [comment]
I also hope he fixes it soon

**Comment by Zarkness2** [comment]
Hi, a question, do you accept suggestions for new flags?

**Comment by Ynfuien** [comment]
I accept giving suggestions. Whether I accept suggestion, depends on given suggestion

**Comment by Zarkness2** [comment]
these were the flags that I thought that could be added, if there is any that you do not understand tell me I do not attend much github, I usually attend more discord, so I leave my tag for you to send me a friend request if you prefer to ask me there `! Zarkness#0291`, if you see that some of them are already in the plugin itself then don't do them directly

flags suggestion:

keep inventory, interaction with candles, this is not possible but I do not think interaction with the cobblestone generator here I mean they can simply break the blocks of the cobblestone generator and if it were possible to make it separate 3 flags 1 for the nether, one for the end and one for the overworld, use of elytras, collect lava, collect water, use the portal of the end and use the portal of the nether, flag to put with which roles of the island the generator works, if it is possible to separate it in 3 to put 1 for the nether, another for the end and another for the overworld it would be appreciated, fire extinguishing, interaction with armor stands, interaction with anvils, interaction with enchantment table, interaction with breawingstand, interaction with craftingtable, abbreviating an interaction option with each of the different work tables, interaction with lectern, interaction with notepad, interaction with touch disks, interaction with boats, interaction with buttons, interaction with beds, interaction with wagons, interaction with shearing, raising animals, interaction with cube, interaction with dispenser, interaction with dropper, interaction with beacons, interaction with labels, allow or disallow the use of the frost walker charm, use of the coral fruit, interaction with the beehives to be able to collect honey, interaction with oven, interaction with dragon egg, use of spawn eggs, allow whether or not they can crush turtle eggs, throw eggs, throw experience bottles, throw experience bottles, use of experience bottles, use of the coral fruit, use of the coral fruit, interaction with the hives to be able to collect honey, interaction with oven, interaction with dragon egg, use of spawn eggs, allow whether or not they can crush turtle eggs, throwing eggs, throwing experience bottles, throwing potions, interaction with itemframes, use of lighter, being able to ride animals, being able to see animals inventory, milking cows, interaction with cakes, use of enderpearl, trampling crops, interaction with pressure plates, interaction with doors, collecting experience, collecting fish, use of dyes, interaction with barrels, interaction with shulker box, interaction with pots

**Comment by Ynfuien** [comment]
I prefer using GitHub for this, so we'll stay here, but thanks for the option.

And so about suggested flags you've mentioned:
1. `keep inventory` - I think, this shouldn't be a flag for players, to just turn off/on. Rather admin should set, or not, keep inventory for SkyBlock world with /gamerule.
2. `interaction with candles` - It's USE_CANDLES. Unfortunately it only works for extinguishing candle, since SS2 blocks using flint and steal with BUILD perm.
3. `interaction with the cobblestone generator` - Do you mean vanilla generator with lava and water or from some other plugin?
4. `use of elytras` - USE_ELYTRA
5. `collect lava` - For some reason SS2's BUILD is responsible for collecting lava/water/snow. So I presume, like with candles, it would block collecting anything, before new flag could do something.
6. `collect water` - ^
7. `use the portal of the end and use the portal of the nether` - I'll try implement it
8. `which roles of the island the generator works` - I think it's the same as no. 3?
9. `fire extinguishing` - SS2's BREAK
10. `interaction with armor stands` - USE_ARMOR_STANDS
11. `interaction with anvils` - USE_ANVILS
12. `interaction with enchantment table` - USE_ENCHANTING_TABLES
13. `interaction with breawingstand` - USE_BREWING_STANDS
14. `interaction with craftingtable` - 
15. `abbreviating an interaction option with each of the different work tables`
16. `interaction with lectern` - USE_LECTERNS
17. `interaction with notepad` - Notepad? You mean note block? USE_NOTE_BLOCKS allow, or not, to change note block's note.
18. `interaction with touch disks` - Jukeboxes? USE_JUKEBOXES
19. `interaction with boats` - SS2's MINECART_ENTER/PLACE/DAMAGE/OPEN. They work for both minecarts and boats
20. `interaction with buttons` - USE_BUTTONS
21. `interaction with beds` - USE_BEDS
22. `interaction with wagons` - No. 19
23. `interaction with shearing` - SS2's ANIMAL_SHEAR
24. `raising animals` - Raising? In what context? For just breeding is SS2's ANIMAL_BREED
25. `interaction with cube` - There are many, many, many cubes in Minecraft, I won't guess this one.
26. `interaction with dispenser` - USE_DISPENSERS
27. `interaction with dropper` - USE_DROPPERS
28. `interaction with beacons` - USE_BEACONS
29. `interaction with labels` - Signs? SS2's SIGN_INTERACT
30. `allow or disallow the use of the frost walker charm` - Like in no. 5, SS2's BUILD
31. `use of the coral fruit` - What is the coral fruit? If you mean chorus fruit then it's EAT_CHORUS_FRUIT.
32. `interaction with the beehives to be able to collect honey`
33. `interaction with oven`
34. `interaction with dragon egg` - PAT_DRAGON_EGG
35. `use of spawn eggs` - SS2's ANIMAL_SPAWN
36. `allow whether or not they can crush turtle eggs` - SS2's TURTLE_EGG_TRAMPINGturtle_egg_tramping
37. `throw eggs`
38. `throw experience bottles`
39. `throw experience bottles`
40. `use of experience bottles`
41. `use of the coral fruit`
42. `use of the coral fruit`
43. `interaction with the hives to be able to collect honey`
44. `interaction with oven`
45. `interaction with dragon egg`
46. `use of spawn eggs`
47. `allow whether or not they can crush turtle eggs`
48. `throwing eggs`
49. `throwing experience bottles`
50. `throwing potions`
51. `interaction with itemframes`
52. `use of lighter`
53. `being able to ride animals`
54. `being able to see animals inventory`
55. `milking cows`
56. `interaction with cakes`
57. `use of enderpearl`
58. `trampling crops`
59. `interaction with pressure plates`
60. `interaction with doors`
61. `collecting experience`
62. `collecting fish`
63. `use of dyes`
64. `interaction with barrels`
65. `interaction with shulker box`
66. `interaction with pots`

**Comment by Ynfuien** [comment]
I prefer using GitHub for this, so we'll stay here, but thanks for the option.

And so about suggested flags you've mentioned:
1. `keep inventory` - I think, this shouldn't be a flag for players, to just turn off/on. Rather admin should set, or not, keep inventory for SkyBlock world with /gamerule.
2. `interaction with candles` - It's USE_CANDLES. Unfortunately it only works for extinguishing candle, since SS2 blocks using flint and steal with BUILD perm.
3. `interaction with the cobblestone generator` - Do you mean vanilla generator with lava and water or from some other plugin?
4. `use of elytras` - USE_ELYTRA
5. `collect lava` - For some reason SS2's BUILD is responsible for collecting lava/water/snow. So I presume, like with candles, it would block collecting anything, before new flag could do something.
6. `collect water` - ^
7. `use the portal of the end and use the portal of the nether` - I'll try implement it
8. `which roles of the island the generator works` - I think it's the same as no. 3?
9. `fire extinguishing` - SS2's BREAK
10. `interaction with armor stands` - USE_ARMOR_STANDS
11. `interaction with anvils` - USE_ANVILS
12. `interaction with enchantment table` - USE_ENCHANTING_TABLES
13. `interaction with breawingstand` - USE_BREWING_STANDS
14. `interaction with craftingtable` - Crafting and all those other work tables can't be used up like e.g. anvil and they don't annoy like e.g. bell, so they don't impact/disturb other players. If you really want a permission for it, then you can add all work tables to `SuperiorSkyblock2/interactables.yml` and use SS2's INTERACT.
15. `abbreviating an interaction option with each of the different work tables` - No. 14
16. `interaction with lectern` - USE_LECTERNS
17. `interaction with notepad` - Notepad? You mean note block? USE_NOTE_BLOCKS allow, or not, to change note block's note.
18. `interaction with touch disks` - Jukeboxes? USE_JUKEBOXES
19. `interaction with boats` - SS2's MINECART_ENTER/PLACE/DAMAGE/OPEN. They work for both minecarts and boats
20. `interaction with buttons` - USE_BUTTONS
21. `interaction with beds` - USE_BEDS
22. `interaction with wagons` - No. 19
23. `interaction with shearing` - SS2's ANIMAL_SHEAR
24. `raising animals` - Raising? In what context? For just breeding is SS2's ANIMAL_BREED
25. `interaction with cube` - There are many, many, many cubes in Minecraft, I won't guess this one.
26. `interaction with dispenser` - USE_DISPENSERS
27. `interaction with dropper` - USE_DROPPERS
28. `interaction with beacons` - USE_BEACONS
29. `interaction with labels` - Signs? SS2's SIGN_INTERACT
30. `allow or disallow the use of the frost walker charm` - Like in no. 5, SS2's BUILD
31. `use of the coral fruit` - What is the coral fruit? If you mean chorus fruit then it's EAT_CHORUS_FRUIT.
32. `interaction with the beehives to be able to collect honey`
33. `interaction with oven` - No. 14
34. `interaction with dragon egg` - PAT_DRAGON_EGG
35. `use of spawn eggs` - SS2's ANIMAL_SPAWN
36. `allow whether or not they can crush turtle eggs` - SS2's TURTLE_EGG_TRAMPING
37. `throw eggs` - THROW_EGGS
38. `throw experience bottles` - I'll implement it
39. `throw experience bottles` - No. 38
40. `use of experience bottles` - No. 38
41. `use of the coral fruit` - No. 31
42. `use of the coral fruit` - No. 31
43. `interaction with the hives to be able to collect honey` - No. 32
44. `interaction with oven` - No. 14
45. `interaction with dragon egg` - No. 34
46. `use of spawn eggs` - No. 35
47. `allow whether or not they can crush turtle eggs` - No. 36
48. `throwing eggs` - No. 37
49. `throwing experience bottles` - No. 38
50. `throwing potions` - THROW_POTIONS
51. `interaction with itemframes` - USE_ITEM_FRAMES and ROTATE_ITEM_FRAME_ITEMS
52. `use of lighter` - Unfortunately SS2's BULD blocks it (No. 2).
53. `being able to ride animals` -I checked and SS2's MINECART_ENTER is also responsible for allowing to ride e.g. pig and strider. For riding horse/mule also SS2's HORSE_INTERACT is needed. 
54. `being able to see animals inventory` - SS2's HORSE_INTERACT
55. `milking cows` - SS2's BUILD problem
56. `interaction with cakes` - EAT_CAKE
57. `use of enderpearl` - SS2's ENDER_PEARL
58. `trampling crops` - SS2's FARM_TRAMPING
59. `interaction with pressure plates` - USE_PRESSURE_PLATES
60. `interaction with doors` - USE_DOORS
61. `collecting experience` - As far as I know, currently it's not possible to implement, or at least not without a big mess.
62. `collecting fish` - SS2's PICKUP_FISH
63. `use of dyes` - Where exactly? For signs is SS2's SIGN_INTERACT
64. `interaction with barrels` - USE_BARRELS
65. `interaction with shulker box` - USE_SHULKER_BOXES
66. `interaction with pots` - USE_FLOWER_POTS

I think I replied for all suggestions. I would like to get more explanation about any that I couldn't understand, and also you can correct me if I misunderstood anything.

**Comment by Zarkness2** [comment]
No. 3: I mean the vanilla lava generator with water apart from the nether generator of version 1.16 onwards which is with packet ice + soul soil + lava.

No. 5-6: I would prefer it separately since I could set if I want them to collect water only or lava or snow.

No. 8: not in this one what I mean is that if SS2 allows it, for example if the owner or the role is not connected, the generators will not work.

No. 14: I would prefer separate because I may want them to have access to the blacksmith table but not to any other.

No. 17: Yes, I made a mistake and meant block's note.

No. 29: Nametags I meant to say.

No. 63: I meant to use dyes either on sheep, signs or anywhere else where dye can be used.

**Comment by Ynfuien** [comment]
No. 3 - Okay, in that case it's not really posible. Vanilla generators don't work because some player is using them, but because lava touched water/ice, so there is no good way to do this.
No. 5-6 - I understand, but without BUILD permission players won't be able to collect anything.
No. 8 - Okay, then it doesn't feel like a permission
No. 14 - Will try implement it 
No. 29 - Then SS2's NAME_ENTITY.
No. 63 - For signs, as I said, is SS2's SIGN_INTERACT. For dyeing entities (sheep, wolf's collar) I will do general permission

**Comment by Ynfuien** [comment]
@Zarkness, just uploaded new [release](https://github.com/Ynfuien/SuperiorSkyblockExtraFlags/releases/tag/2.0.0). Read changes and updated README

**Comment by Zarkness2** [comment]
okey thanks

**Comment by Zarkness2** [comment]
@Ynfuien add the player_damage flag so that they can choose which role takes damage and which one does not take damage
